version: "3.3"

services:
  shop:
    build:
      dockerfile: Shop/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8180:8080"
  
  stock:
    build:
      dockerfile: Stock/Dockerfile
    ports:
      - "8280:8080"

  payments:
    build:
      dockerfile: Payments/Dockerfile
    ports:
      - "8380:8080"
